;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_a
	.export		_loop
	.export		_reset

.segment	"BSS"

_a:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ loop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_loop: near

.segment	"CODE"

	ldx     #$00
	lda     #$04
	sta     _a
	stx     _a+1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ reset (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reset: near

.segment	"CODE"

	ldx     #$00
	lda     #$03
	sta     _a
	stx     _a+1
	jsr     _loop
	rts

.endproc

