// Code generated by "stringer -type=StatusFlags"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C-1]
	_ = x[Z-2]
	_ = x[I-4]
	_ = x[D-8]
	_ = x[B-16]
	_ = x[Unused-32]
	_ = x[V-64]
	_ = x[N-128]
}

const (
	_StatusFlags_name_0 = "CZ"
	_StatusFlags_name_1 = "I"
	_StatusFlags_name_2 = "D"
	_StatusFlags_name_3 = "B"
	_StatusFlags_name_4 = "Unused"
	_StatusFlags_name_5 = "V"
	_StatusFlags_name_6 = "N"
)

var (
	_StatusFlags_index_0 = [...]uint8{0, 1, 2}
)

func (i StatusFlags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _StatusFlags_name_0[_StatusFlags_index_0[i]:_StatusFlags_index_0[i+1]]
	case i == 4:
		return _StatusFlags_name_1
	case i == 8:
		return _StatusFlags_name_2
	case i == 16:
		return _StatusFlags_name_3
	case i == 32:
		return _StatusFlags_name_4
	case i == 64:
		return _StatusFlags_name_5
	case i == 128:
		return _StatusFlags_name_6
	default:
		return "StatusFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
