// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package instruction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Acc-0]
	_ = x[Abs-1]
	_ = x[AbsX-2]
	_ = x[AbsY-3]
	_ = x[Immediate-4]
	_ = x[Impl-5]
	_ = x[Ind-6]
	_ = x[Xind-7]
	_ = x[IndY-8]
	_ = x[Rel-9]
	_ = x[Zpg-10]
	_ = x[ZpgX-11]
	_ = x[ZpgY-12]
}

const _Mode_name = "AccAbsAbsXAbsYImmediateImplIndXindIndYRelZpgZpgXZpgY"

var _Mode_index = [...]uint8{0, 3, 6, 10, 14, 23, 27, 30, 34, 38, 41, 44, 48, 52}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
