// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package instruction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADC-0]
	_ = x[AND-1]
	_ = x[ASL-2]
	_ = x[ASL_ACC-3]
	_ = x[BCC-4]
	_ = x[BCS-5]
	_ = x[BEQ-6]
	_ = x[BIT-7]
	_ = x[BMI-8]
	_ = x[BNE-9]
	_ = x[BPL-10]
	_ = x[BRK-11]
	_ = x[BVC-12]
	_ = x[BVS-13]
	_ = x[CLC-14]
	_ = x[CLD-15]
	_ = x[CLI-16]
	_ = x[CLV-17]
	_ = x[CMP-18]
	_ = x[CPX-19]
	_ = x[CPY-20]
	_ = x[DEC-21]
	_ = x[DEX-22]
	_ = x[DEY-23]
	_ = x[EOR-24]
	_ = x[INC-25]
	_ = x[INX-26]
	_ = x[INY-27]
	_ = x[JMP-28]
	_ = x[JSR-29]
	_ = x[LDA-30]
	_ = x[LDX-31]
	_ = x[LDY-32]
	_ = x[LSR-33]
	_ = x[LSR_ACC-34]
	_ = x[NOP-35]
	_ = x[ORA-36]
	_ = x[PHA-37]
	_ = x[PHP-38]
	_ = x[PLA-39]
	_ = x[PLP-40]
	_ = x[ROL-41]
	_ = x[ROL_ACC-42]
	_ = x[ROR-43]
	_ = x[ROR_ACC-44]
	_ = x[RTI-45]
	_ = x[RTS-46]
	_ = x[SBC-47]
	_ = x[SEC-48]
	_ = x[SED-49]
	_ = x[SEI-50]
	_ = x[STA-51]
	_ = x[STX-52]
	_ = x[STY-53]
	_ = x[TAX-54]
	_ = x[TAY-55]
	_ = x[TSX-56]
	_ = x[TXA-57]
	_ = x[TXS-58]
	_ = x[TYA-59]
}

const _Opcode_name = "ADCANDASLASL_ACCBCCBCSBEQBITBMIBNEBPLBRKBVCBVSCLCCLDCLICLVCMPCPXCPYDECDEXDEYEORINCINXINYJMPJSRLDALDXLDYLSRLSR_ACCNOPORAPHAPHPPLAPLPROLROL_ACCRORROR_ACCRTIRTSSBCSECSEDSEISTASTXSTYTAXTAYTSXTXATXSTYA"

var _Opcode_index = [...]uint8{0, 3, 6, 9, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 103, 106, 113, 116, 119, 122, 125, 128, 131, 134, 141, 144, 151, 154, 157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
